### ISSUE TITLE
create_lan() throws AttributeError

### ISSUE THREAD

**Issue by bdrung** [profitbricks/profitbricks-sdk-python#10]
This code (running against current master branch):
```
lan1 = LAN(public=True, nics=[])
create_lan('aa0df8f8-530a-468f-8006-6b870804932e', lan1)
```
causes this exception:
```
[...]/profitbricks/client.py in create_lan(self, datacenter_id, lan)
    597         data = self._underscore_to_camelcase(
    598             json.dumps(
--> 599                 self._create_lan_dict(lan)
    600                 )
    601             )

[...]/profitbricks/client.py in _underscore_to_camelcase(self, value)
   1791 
   1792         c = camelcase()
-> 1793         return "".join(c.next()(x) if x else '_' for x in value.split("_"))
   1794 
   1795     def _create_lan_dict(self, lan):

[...]/profitbricks/client.py in <genexpr>(.0)
   1791 
   1792         c = camelcase()
-> 1793         return "".join(c.next()(x) if x else '_' for x in value.split("_"))
   1794 
   1795     def _create_lan_dict(self, lan):

AttributeError: 'generator' object has no attribute 'next'
```
A workaround is to remove the ```self._underscore_to_camelcase``` call from the ```create_lan()``` method and use the output of ```json.dumps()``` directly.

**Comment by edevenport** [comment]
@bdrung I tested the above (Python 2.7 and 3.4) and was not able to duplicate. Can you test with the latest 2.3.1 SDK and let us know if you still encounter the error?

**Comment by edevenport** [comment]
If you still encounter the issue, please reopen the ticket and include OS, Python version, and library version being used.

**Comment by bdrung** [comment]
I retested the code snipped with Python 3.4.3 and profitbricks-sdk-python 2.3.1 and the problem is gone.
