### ISSUE TITLE
lacking option for cert (or verify=False)

### ISSUE THREAD

**Issue by grandvizier** [profitbricks/profitbricks-sdk-python#11]
When using the sdk to run against a staging environment, the obfuscated request calls don't allow for a certificate file to be passed (or at the very least: `verify=False`), thereby resulting in the following error:
* `requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed`

**Comment by bdrung** [comment]
Have you considered using correctly signed certificates in the staging environment?

**Comment by baldwinSPC** [comment]
@grandvizier this is an odd request as the module's intent is to work against the public ProfitBricks REST API. What's the reason to support non-public environments with the library?

**Comment by botchniaque** [comment]
When can we expect updated pip package?

**Comment by edevenport** [comment]
@botchniaque - I am running the latest PR merges and my branch against the live tests now. Once I confirm they pass across multiple Python versions, then I will release an updated pip package. If all goes well, hope to complete this today.
