### ISSUE TITLE
Creating NICs has incorrect handling of Booleans

### ISSUE THREAD

**Issue by jbuchhammer** [profitbricks/profitbricks-sdk-python#25]
When NICs are created via `create_nic()` or `create_server()` the Boolean values for the properties `dhcp` and `firewall_active` are correctly handled.
E.g. setting `dhcp=False` has no effect. The created NIC will end up with `dhcp=True`.

Creation of NICs uses `_create_nic_dict()` which maps a NIC object's properties to JSON format.
For Boolean properties this is performed like
```
if nic.dhcp:
    properties['dhcp'] = nic.dhcp
```
So, if the property is False, the mapping is skipped.

**Comment by jbuchhammer** [comment]
Started fixing on fork https://github.com/jbuchhammer/profitbricks-sdk-python

**Comment by edevenport** [comment]
PR #26 has been merged into master and pushed new release.
