### ISSUE TITLE
Volume Creation failed

### ISSUE THREAD

**Issue by mnietz** [profitbricks/profitbricks-sdk-python#35]
I use python: 2.7.9 with api 2.3.2

When i try to create a volume based on the Debian 8 Image in the Frankfurt Location i get the error:

**"Passwords/SSH Keys are mandatory for public ProfitBricks Images"**

According the Cloud-APIv2 Docs:

https://devops.profitbricks.com/api/cloud/v2/#whats-new

This can be specified either by providing imagePassword or sshKeys. I tried both and still receive the error message

```
volume1 = Volume(
    name='server1-boot',
    size=12,
    imagePassword='foobarbaz',
    sshKeys=['ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB.........'],
    image='c7f1084d-27a8-11e6-8e88-52540005ab80',
    )

response = client.create_volume(
    datacenter_id=datacenter_id, volume=volume1)
```

What am i doing wrong ?

**Comment by edevenport** [comment]
Hello @mnietz  - it looks the like the parameters you are passing to the Volume class are incorrect. The Python SDK uses instance variables that are lower case and separated with underscores. In your example:

`imagePassword` should be `image_password`
`sshKeys` should be `ssh_keys`

Here is the related class definition in the SDK:

    class Volume(ProfitBricksService):
        def __init__(self, name=None, size=None, bus='VIRTIO', image=None,
                     disk_type='HDD', licence_type='UNKNOWN', image_password=None,
                     ssh_keys=[], **kwargs):

The documentation should be updated with more examples, but `pydoc` will list the proper parameters.

    pydoc profitbricks.client.Volume

Please let me know if you encounter any further issues.

**Comment by fbrehm** [comment]
Hello @mnietz,

I could verify, that the arguments were incorrect. I have executed a test with the following Volume definition:

    Volume(
        name='test-debian-vda', size=20,
        image='bba01709-3f3b-11e6-91c6-52540005ab80', bus='VIRTIO',
        image_password='foobarbaz', ssh_keys=['ssh-rsa AAAAB3NzaC1yc2EA...']
    )

and everything was fine.

**Comment by mnietz** [comment]
Hello,

thanks for your help, it works fro me now.
