### ISSUE TITLE
Fix NIC.dhcp bool-to-str convertion

### ISSUE THREAD

**Issue by nolar** [profitbricks/profitbricks-sdk-python#36]
In the code of `create_nic()`, you have:

```
properties['dhcp'] = str(loadbalancer.dhcp).lower()
```

If the NIC was created with dhcp set to any explession that returns an object, but not True/False, this would lead to sending a string representation of the object to the API. 

Easy fix — convert it to a boolean first:

```
properties['dhcp'] = str(bool(loadbalancer.dhcp)).lower()
```

The same is for `LoadBalancer.dhcp`.

The same is for `NIC.__repr__` and `LoadBalancer.__repr__`.

**Comment by edevenport** [comment]
I tested the create_nic method and the `dhcp` value currently supports `True` and `False` booleans as well as `"true"`, `"True"`, `"false"`, and `"False"` strings. I feel this covers most situations and I would expect any other value to result in an exception.

If we explicitly set the value to a boolean as suggested, then this would result in converting `"False"` or `"false"` strings to `True`. This is likely to cause confusion.

**Comment by nolar** [comment]
Maybe you should handle all special cases explicitly.

This case can cause problems. We want dhcp only if we have any ips assigned to the NIC, otherwise no DHCP. Just as a sample case, not real yet. Here, we check for object to evaluate to true, ie being non-empty. I will have to force-convert it to `bool()`, but this is not always done.

```
ipblock = MyOwnIPBlockObject(size=5)
default_ips = ['10.10.10.10']
NIC(..., dhcp=ipblock or default_ipset)
```

**Comment by edevenport** [comment]
This is not something the ProfitBricks SDK will support. The SDK follows the behavior of the ProfitBricks REST API which is to accept `true` if you want DHCP enabled or `false` if you want DHCP disabled. The default behavior of both the SDK and REST API is to enable DHCP unless it is set to `false`. The `dhcp` property value should not be used to evaluate whether an object exists or not. That logic is better handled prior to defining the NIC.
