### ISSUE TITLE
ICMP type 0 (ping reply) / code 0 not supported

### ISSUE THREAD

**Issue by nolar** [profitbricks/profitbricks-sdk-python#37]
Trying to pass icmp_type=0 or icmp_code=0 (integers, not strings) to `FirewallRule` lead to these fields missing from the HTTP request because of this code (integer 0 evaluates to false):

```
if firewall_rule.icmp_type:
    properties['icmpType'] = firewall_rule.icmp_type

if firewall_rule.icmp_code:
    properties['icmpCode'] = firewall_rule.icmp_code
```

ICMP type 0 is ping reply (ping request is type 8). 

As a result, these values are missing from the resuling firewall rules:

![image](https://cloud.githubusercontent.com/assets/544296/16492402/f20a0816-3ee1-11e6-82c9-0c9c05955dff.png)

**Comment by edevenport** [comment]
@nolar - This should be corrected now.
