### ISSUE TITLE
example script pb_addNewServer.py has wrong default for DHCP

### ISSUE THREAD

**Issue by jbuchhammer** [profitbricks/profitbricks-sdk-python#41]
The example script `pb_addNewServer.py` adds a new server to an existing datacenter and connects it to a specified LAN.

The server's NIC is created with `dhcp=False` as default value.
This is in contrast to the standard of the API and SDK where the dafult value is `True`

The default value in this script must be the same as in API and SDK to avoid unexpected behaviour.

**Comment by edevenport** [comment]
PR has been merged into master.
