### ISSUE TITLE
The upgrade to handle cloudapi v3 is not backwards compatible

### ISSUE THREAD

**Issue by grandvizier** [profitbricks/profitbricks-sdk-python#45]
The change to all availabilityZone for Volumes breaks rest versions 1 & 2 usage
https://github.com/profitbricks/profitbricks-sdk-python/commit/f3d7de308381981e71d100777edeb8ae6b65faea#diff-a6b8a93c04c0a636e1e6472d1b33762eR2263

availabilityZone is not required in v3, and therefor should not be defaulted to `AUTO`
```
availabilityZone	string	The storage availability zone assigned to the volume. Valid values: AUTO, ZONE_1, ZONE_2, or ZONE_3. This only applies to HDD volumes. Leave blank or set to AUTO when provisioning SSD volumes.	No
```
https://devops.profitbricks.com/api/cloud/v3/#create-volume

**Comment by jasminSPC** [comment]
Sorry for the inconvenience.

Give it a try now
