### ISSUE TITLE
Mention provisioning states in manual

### ISSUE THREAD

**Issue by fho** [profitbricks/profitbricks-sdk-python#5]
After resource is created (datacenter, server, etc) it may take some time until it is created.
A script has to poll the state attribute of a object until it is '???' before proceeding with further operations on the instance.

- Add a description for that to the manual and mention which states exist and what they mean.
- an example function to wait until a object was provisioned could also be helpful

**Comment by edevenport** [comment]
The README.md in the master branch has been updated.
