### ISSUE TITLE
Throw API specific Exceptions instead of using the Exception class

### ISSUE THREAD

**Issue by fho** [profitbricks/profitbricks-sdk-python#6]
When errors happen inside the API, always Exceptions from type Exception are thrown.
This makes it impossible to:
- determine if an exception came from the API or other code in the script
- react depending on the type of error

Instead create an own Exception class deriving from Exception and throw this one. Even better would be to use different type of exceptions depending on the error, e.g:
PBNotAuthorizedError
PBRessourceDoesNotExist

**Comment by jbuchhammer** [comment]
I strongly support this, especially having a PBRessourceDoesNotExist exception.
Consider for example creation of new Servers with disk images or snapshots. If these were deleted by some one else, it will considerably reduce debugging effort to know, that the image is not available anymore.
And that scenario is not too academic, if one keeps in mind, that the ProfitBricks disk images are exchanged every month.
