### ISSUE TITLE
lower logging priority for "Starting new HTTPS connection"

### ISSUE THREAD

**Issue by fho** [profitbricks/profitbricks-sdk-python#7]
The library logs the following message with INFO priority:
> INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.profitbricks.com

The priority should be lowered to debug. The message appears quite often when the API is used in a simple script to create servers and doesn't provide meaningful information.

**Comment by edevenport** [comment]
@fho - the `profitbricks-sdk-python` library does not presently require logging as a dependency. The logging level is defined by the `requests` library and can be override in your script with the following:

    import logging
    logging.basicConfig(level=logging.INFO)
    logging.getLogger('requests').setLevel(logging.ERROR)

This should allow the user to set the desired level of logging without forcing the decision through the SDK.

**Comment by fho** [comment]
ok, thanks
